name: ini_v2
version: 1.0.0
homepage: https://github.com/dhzdhd/dart-ini
description: Read and write .ini files

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: any
  stream_channel: any
